//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MultiClick.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDD_ABOUT                       100
#define IDS_ABOUTBOX                    101
#define IDD_WBP_DIALOG                  102
#define IDR_MENU_DEMO                   129
#define IDR_SYSMENU                     129
#define IDD_MULTICLICK_DIALOG           130
#define IDB_HELP                        134
#define IDB_OPTION                      136
#define IDB_CHECK                       138
#define IDB_MENU_CLOSE                  139
#define IDB_ABOUT                       140
#define IDD_CONFIGDLG                   141
#define IDD_KEY_DIALOG                  142
#define IDR_MENU1                       143
#define IDR_RT_MANIFEST1                144
#define IDD_SETTING                     146
#define IDB_BACKGROUND                  154
#define IDB_DEFAULT                     156
#define IDD_AUTHOR                      157
#define IDB_AUTHOR                      158
#define IDB_BUTTON                      159
#define IDR_MAINFRAME                   169
#define IDI_LEDOFF                      171
#define IDI_LEDON                       172
#define IDI_DISABLE                     173
#define IDI_SOUND                       174
#define IDB_INFOKEY                     175
#define IDD_READ                        176
#define IDD_SERVER                      177
#define IDB_SERVER                      178
#define IDB_EMAIL                       179
#define IDB_R                           180
#define IDB_DICTIONARY                  181
#define IDI_CONNECT                     182
#define IDI_DISCONNECT                  183
#define IDD_AUTOUPDATE_VERSION          183
#define IDD_READTEXT                    184
#define IDD_DICTIONARY                  186
#define IDD_DICTIONARYDLG               186
#define IDI_SERVER                      187
#define IDI_AUTHOR                      188
#define IDI_ICON1                       189
#define IDI_TASKBAR                     190
#define IDI_CANCEL                      191
#define IDI_ICON2                       192
#define IDI_DICT                        192
#define IDC_EXPLORER1                   1000
#define IDC_AUTOUPDATE                  1000
#define IDC_CHARSET                     1001
#define IDC_CHECK_NEW_VERSION           1001
#define IDC_INPUT_METHOD                1002
#define IDC_READ_SHOW                   1002
#define IDC_SWKEY1                      1003
#define IDC_READ_TURN_OFF               1003
#define IDC_SWKEY2                      1004
#define IDC_CONNECT                     1004
#define IDC_FREE_MARKING                1005
#define IDC_PROGRESS1                   1005
#define IDC_U_CLIPBOARD                 1006
#define IDC_KEY_TASKBAR                 1007
#define IDC_CTRL                        1008
#define IDC_AUTOUPDATE_BTN              1008
#define IDC_SHIFT                       1009
#define IDC_NO_KEYBOARD                 1010
#define IDC_CURRENTDICT                 1010
#define IDC_RIGHT_CLICK                 1011
#define IDC_BACKGROUND                  1012
#define IDC_TEXTCOLOR                   1013
#define IDC_NGUNG                       1013
#define IDC_TITLECOLOR                  1014
#define IDC_DUNG                        1014
#define IDC_CLOSEMODE                   1015
#define IDC_AUTOSTART                   1016
#define IDC_ABOUT                       1018
#define IDC_SLIDER1                     1018
#define IDC_SLIDER2                     1019
#define IDC_GUILANGUAGE                 1020
#define IDC_COMBO1                      1021
#define IDC_EDIT1                       1022
#define IDC_URL                         1022
#define IDC_TASKBAR                     1024
#define IDC_STATIC2                     1030
#define IDC_STATIC1                     1031
#define ID_ABOUT_OK                     1033
#define IDC_LISTPAGE                    1034
#define IDC_PANEL                       1035
#define IDC_BUTTON1                     1036
#define IDC_TEXTBOX                     1036
#define IDC_SOUND                       1037
#define IDC_KEEPIT                      1038
#define IDC_STATIC3                     1042
#define IDC_IDC_NO_KEYBOARD             1050
#define IDC_MOFILE                      1050
#define IDC_DOCVB                       1051
#define IDC_CANCEL                      1052
#define IDC_STATIC11                    1055
#define IDC_STATIC12                    1056
#define IDC_STATIC13                    1057
#define IDC_STATIC14                    1058
#define IDC_STATIC15                    1059
#define IDC_STATIC21                    1060
#define IDC_STATIC22                    1061
#define IDC_STATIC4                     1062
#define IDC_STATIC5                     1063
#define IDC_STATIC6                     1064
#define IDC_STATIC7                     1065
#define IDC_STATIC8                     1066
#define IDC_STATICM                     1067
#define IDC_STATIC9                     1068
#define _APS_NEXT_CONTROL_TALUE         1069
#define ID_DEMO_PRINTPREVIEW            32771
#define ID_DEMO_PAGESETUP               32775
#define ID_DICTIONARY                   32780
#define ID_OPEN_HELP                    32785
#define ID_KEY_CONF                     32788
#define ID_KEY_UNICODE                  32789
#define ID_KEY_VIQR                     32790
#define ID_KEY_ON                       32794
#define ID_KEY_VIETWAREF                32795
#define ID_KEY_VIETWAREX                32801
#define ID_KEY_BKHCM1                   32802
#define ID_KEY_BKHCM2                   32803
#define ID_KEY_VPS                      32804
#define ID_KEY_VISCII                   32805
#define ID_KEY_VNI                      32806
#define ID_TELEX_TYPING                 32807
#define ID_VNI_TYPING                   32808
#define ID_KEY_TCVN3                    32810
#define ID_AUTOLOOK_ON                  32811
#define ID_ONLYTEXT                     32816
#define ID_SHIFT_CLICK                  32817
#define ID_CTRL_CLICK                   32818
#define ID_CLICK                        32819
#define ID_LOOKUPON_ENGLISH             32821
#define ID_LOOKUPON_FRANCE              32822
#define ID_LOOKUPON_GERMANY             32823
#define ID_LOOKUPON_VIETNAMESE          32824
#define ID_LOOKUPON_AUTOMATIC           32825
#define ID_LOOKUPON_RUSSIA              32826
#define ID_LOOKUPON_NAUY                32828
#define ID_SYSMENU_ONLINEFEATURES       32829
#define ID_DICTIONARYONLINE             32832
#define ID_LOOKUPONLINE                 32833
#define ID_UPDATEDICTONARY              32836
#define ID_END                          32837
#define ID_PANEL                        32838
#define ID_DICTIONARYONLINE_ANHVIET     32839
#define ID_DICTIONARYONLINE_PH          32840
#define ID_DICTIONARYONLINE_DUC         32841
#define ID_DICTIONARYONLINE_NGAVIETDICT 32842
#define ID_DICTIONARYONLINE_NAUYVIETDICT 32843
#define ID_Menu                         32844
#define ID_ONLINEFEATURES_DICTIONARYONLINE 32845
#define ID_INFOKEY                      32847
#define ID_DICTIONARY_ENGLISHV          32852
#define ID_DICTIONARY_FRANCEV           32853
#define ID_DICTIONARY_GERMANYV          32854
#define ID_DICTIONARY_NAUY_NV           32855

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32856
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
